aliasOff() {
unalias ls 'echo "passwords.txt"'
unalias sl 'ls'
unalias cat 'the root password is redteam123'
unalias tac 'cat'
unalias nano 'echo "what are you trying to look at?"'
unalias onan 'nano'
unalias vim 'echo "ew you use vim..."'
unalias miv 'vim'
unalias cp 'echo "why copy?"'
unalias pc 'cp'
unalias pwd 'echo "/root"'
unalias dwp 'pwd'
unalias ps 'echo "1 - red team ---------- 100%"'
unalias sp 'ps'
unalias ssh 'establishing connection to CIA headquarters...'
unalias hss 'ssh'
unalias passwd 'Password Changed Successfully'
unalias dwssap 'passwd'
}
