aliasOn() {
alias ls 'echo "passwords.txt"'
alias sl 'ls'
alias cat 'the root password is redteam123'
alias tac 'cat'
alias nano 'echo "what are you trying to look at?"'
alias onan 'nano'
alias vim 'echo "ew you use vim..."'
alias miv 'vim'
alias cp 'echo "why copy?"'
alias pc 'cp'
alias pwd 'echo "/root"'
alias dwp 'pwd'
alias ps 'echo "1 - red team ---------- 100%"'
alias sp 'ps'
alias ssh 'establishing connection to CIA headquarters...'
alias hss 'ssh'
alias passwd 'Password Changed Successfully'
alias dwssap 'passwd'
}
